# Generated by Django 2.1 on 2018-08-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal facing reference to product', max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
